apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api-deployment
  labels:
    app: weather-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - name: weather-api
          image: anshik2k4/weather-api:latest
          ports:
            - containerPort: 80