apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # These values must be base64 encoded.
  # Example: echo -n "admin" | base64  -> YWRtaW4=
  mongo-root-username: YWRtaW4=       # admin
  mongo-root-password: cGFzc3dvcmQxMjM=   # password123
