name: Deploy To EC2

on:
  push:
    branches: [main]
    paths:
      - 'Quora-Post/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd /home/ubuntu/project
            git pull origin main
            cd Quora-Post
            docker compose down
            docker compose up --build -d